{{- if .Values.global.kioskEnabled -}}
apiVersion: config.kiosk.sh/v1alpha1
kind: Account
metadata:
  labels:
    {{- include "cd-pipeline-operator.labels" . | nindent 4 }}
  name: {{ .Values.global.edpName }}
spec:
  space:
    clusterRole: kiosk-space-admin
  subjects:
    - kind: ServiceAccount
      name: edp-{{ .Values.name }}
      namespace: {{ .Values.global.edpName }}
{{- end -}}
