---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - create
  - delete
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  - serviceaccounts
  verbs:
  - create
- apiGroups:
  - external-secrets.io
  resources:
  - externalsecrets
  - secretstores
  verbs:
  - create
- apiGroups:
  - rbac.authorization.k8s.io
  resourceNames:
  - admin
  resources:
  - clusterroles
  verbs:
  - bind
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - rolebindings
  verbs:
  - create
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: manager-role
  namespace: placeholder
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - create
  - get
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - get
  - list
  - update
  - watch
- apiGroups:
  - argoproj.io
  resources:
  - applicationsets
  verbs:
  - create
  - get
  - update
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - create
  - get
  - update
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - rolebindings
  verbs:
  - create
  - delete
  - get
- apiGroups:
  - rbac.authorization.k8s.io
  resourceNames:
  - external-secret-integration
  resources:
  - roles
  verbs:
  - bind
  - get
- apiGroups:
  - v2.edp.epam.com
  resources:
  - cdpipelines
  verbs:
  - get
  - list
  - update
  - watch
- apiGroups:
  - v2.edp.epam.com
  resources:
  - cdpipelines/finalizers
  - stages/finalizers
  verbs:
  - update
- apiGroups:
  - v2.edp.epam.com
  resources:
  - cdpipelines/status
  - stages/status
  verbs:
  - get
  - update
- apiGroups:
  - v2.edp.epam.com
  resources:
  - codebaseimagestreams
  verbs:
  - create
  - get
  - list
  - update
- apiGroups:
  - v2.edp.epam.com
  resources:
  - codebases
  verbs:
  - get
  - list
- apiGroups:
  - v2.edp.epam.com
  resources:
  - gitservers
  verbs:
  - get
- apiGroups:
  - v2.edp.epam.com
  resources:
  - stages
  verbs:
  - deletecollection
  - get
  - list
  - patch
  - update
  - watch
