{{- if and (eq .Values.tenancyEngine "capsule") (eq .Values.global.platform "kubernetes") .Values.manageNamespace .Values.capsuleTenant.create -}}
apiVersion: capsule.clastix.io/v1beta1
kind: Tenant
metadata:
  labels:
    {{- include "cd-pipeline-operator.labels" . | nindent 4 }}
  name: edp-workload-{{ .Release.Namespace }}
spec:
  owners:
    - kind: ServiceAccount
      name: system:serviceaccount:{{ .Release.Namespace }}:edp-cd-pipeline-operator
{{- if .Values.capsuleTenant.spec }}
  {{- toYaml .Values.capsuleTenant.spec | nindent 2 }}
{{- end }}
{{- end }}
