apiVersion: v2
description: A Helm chart for KubeRocketCI CD Pipeline Operator
home: https://docs.kuberocketci.io/
name: cd-pipeline-operator
type: application
version: 2.23.0-SNAPSHOT
appVersion: 2.23.0-SNAPSHOT
icon: https://docs.kuberocketci.io/img/logo.svg
keywords:
  - edp
  - operator
  - pipelines
  - cd
maintainers:
  - name: epmd-edp
    email: SupportEPMD-EDP@epam.com
    url: https://solutionshub.epam.com/solution/kuberocketci
  - name: sergk
    url: https://github.com/SergK
sources:
  - https://github.com/epam/edp-cd-pipeline-operator
annotations:
  artifacthub.io/license: Apache-2.0
  artifacthub.io/operator: "true"
  artifacthub.io/images: |
    - name: cd-pipeline-operator:2.22.0
      image: epamedp/cd-pipeline-operator:2.22.0
  artifacthub.io/operatorCapabilities: Full Lifecycle
  artifacthub.io/crds: |
    - kind: CDPipeline
      version: v2.edp.epam.com/v1
      name: cdpipeline
      displayName: CDPipeline
      description: Predefined configuration for EDP CDPipelines
    - kind: Stage
      version: v2.edp.epam.com/v1
      name: stage
      displayName: Stage
      description: CD Stage management
  artifacthub.io/crdsExamples: |
    - apiVersion: v2.edp.epam.com/v1
      kind: CDPipeline
      metadata:
        name: clone-edp-javascript
      spec:
        applications:
          - javascript-clone-deploy-edp
        applicationsToPromote:
          - javascript-clone-deploy-edp
        deploymentType: container
        inputDockerStreams:
          - javascript-clone-deploy-edp-clone
        name: clone-edp-javascript
    - apiVersion: v2.edp.epam.com/v1
      kind: Stage
      metadata:
        name: release-github-javascript-dev
      spec:
        cdPipeline: release-github-javascript
        description: dev
        name: dev
        order: 0
        qualityGates:
          - autotestName: null
            branchName: null
            qualityGateType: manual
            stepName: approve
        source:
          library: {}
          type: default
        triggerType: Auto
        triggerTemplate: deploy
  artifacthub.io/links: |
    - name: KubeRocketCI Documentation
      url: https://docs.kuberocketci.io
    - name: EPAM SolutionHub
      url: https://solutionshub.epam.com/solution/kuberocketci
