{{- if eq .Values.global.platform "openshift" -}}
apiVersion: authorization.openshift.io/v1
kind: Role
metadata:
  namespace: {{ .Values.global.edpName }}
  labels:
    {{- include "cd-pipeline-operator.labels" . | nindent 4 }}
  name: edp-{{ .Values.name }}
rules:
- apiGroups:
    - '*'
  resources:
    - cdpipelines
    - cdpipelines/finalizers
    - cdpipelines/status
    - jenkinsfolders
    - jenkinsfolders/finalizers
    - jenkinsfolders/status
    - jenkinsjobs
    - jenkinsjobs/finalizers
    - jenkinsjobs/status
    - codebases
    - codebases/finalizers
    - codebases/status
    - codebasebranches
    - codebasebranches/finalizers
    - codebasebranches/status
    - stages
    - stages/finalizers
    - stages/status
    - gitservers
    - gitservers/status
    - gitservers/finalizers
    - edpcomponents
    - edpcomponents/finalizers
    - edpcomponents/status
    - codebaseimagestreams
    - codebaseimagestreams/status
    - codebaseimagestreams/finalizers
    - configmaps
  verbs:
    - '*'
- apiGroups:
    - coordination.k8s.io
  resources:
    - leases
  verbs:
    - create
    - get
    - list
    - update
- apiGroups:
    - 'apps'
  resources:
    - deployments
  verbs:
    - get
    - list
- apiGroups:
    - '*'
  resources:
    - deploymentconfigs
  verbs:
    - get
    - list
{{- if not .Values.global.kioskEnabled }}
- apiGroups:
    - ""
  resources:
    - namespaces
  verbs:
    - get
    - list
    - create
    - delete
{{- end -}}
{{ end }}
