{{- if eq .Values.secretManager "own" -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
      {{- include "cd-pipeline-operator.labels" . | nindent 4 }}
  name: secret-manager-own-{{ .Release.Namespace }}
rules:
  - apiGroups: [ "" ]
    resources:
      - secrets
    verbs:
      - create
    resourceNames:
      - regcred

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    {{- include "cd-pipeline-operator.labels" . | nindent 4 }}
  name: secret-manager-own-{{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: secret-manager-own-{{ .Release.Namespace }}
subjects:
  - kind: ServiceAccount
    name: edp-{{ .Values.name }}
    namespace: {{ .Release.Namespace }}

{{- end -}}
