apiVersion: v1
kind: ServiceAccount
metadata:
  name: edp-{{ .Values.name }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "cd-pipeline-operator.labels" . | nindent 4 }}
