{{ if eq .Values.global.platform "kubernetes" }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: edp-{{ .Values.global.edpName }}-deployment-view
  labels:
    {{- include "cd-pipeline-operator.labels" . | nindent 4 }}
rules:
- apiGroups:
    - 'apps'
  resources:
    - deployments
  verbs:
    - get
    - list
- apiGroups:
    - '*'
  resources:
    - deploymentconfigs
  verbs:
    - get
    - list
{{ end}}